### ISSUE TITLE
Use public image of substra-tools in the fixtures

### ISSUE THREAD

**Issue by ClementGautier** [SubstraFoundation/substra-backend#16]
As a consequence of the move from gcr.io to docker hub we can now make use of the public images of `substrafoundation/substra-tools` instead of `eu.gcr.io/substra-208412/substra-tools`

There are references of this image in the Dockerfiles and charts here:
```
charts/substra-backend/values.yaml
12:    # - eu.gcr.io/substra-208412/substra-tools:0.0.1

fixtures/chunantes/objectives/objective0/Dockerfile
1:FROM eu.gcr.io/substra-208412/substra-tools:0.0.1

fixtures/owkin/objectives/objective0/Dockerfile
1:FROM eu.gcr.io/substra-208412/substra-tools:0.0.1
```

but also inside the zip and tar.gz files here:
```
./fixtures/chunantes/algos/algo0/algo.zip
./fixtures/chunantes/algos/algo4/algo.zip
./fixtures/chunantes/algos/algo2/algo.zip
./fixtures/chunantes/algos/algo1/algo.tar.gz
./fixtures/chunantes/algos/algo3/algo.tar.gz
./fixtures/chunantes/algos/algo0/algo.tar.gz
./fixtures/chunantes/algos/algo4/algo.tar.gz
```

I may have forgot a location but it should cover all the cases we use right now.

**Comment by 1e3oss** [comment]
Hello, I am willing to work on this issue for Hacktoberfest. Forking the project. For the compressed files the aim is to change the contents and commit updated archives ?

**Comment by ClementGautier** [comment]
Great! Yes this is the idea ;)

**Comment by Kelvin-M** [comment]
@ClementGautier It's done by #21  so I close it, feel free to re-open if something is missing !
