### ISSUE TITLE
Fix swagger doc

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra-backend#185]
The current auto-generated swagger documentation (`/doc`) is broken, probably as a result of our last DRF update.

The [library it relied on](https://marcgibbons.com/django-rest-swagger/) is also deprecated since mid-2019, so instead of just fixing it we'll need to switch to something new.

A potential replacement is https://github.com/axnsan12/drf-yasg

We need to make sure that the fix swagger doc specifies correctly how file uploads are handled. That was the purpose of the `SchemaGenerator` class in `backend/views.py`.

**Comment by Kelvin-M** [comment]
Close as swagger has been removed : https://github.com/SubstraFoundation/substra-backend/pull/364
Feel free to re-open another issue to add api documentation if needed !
