### ISSUE TITLE
Create an aggregatetuple without in model key

### ISSUE THREAD

**Issue by maeldebon** [SubstraFoundation/substra-backend#187]
# Original issue from the `substra` repository

> It is possible to create an aggregatetuple without passing any --in-model-key in the command.

# Issue in the backend

The `in_models_keys` field of an aggregatetuple isn't required and has a minimum length of 0. 

As the sole purpose of the aggregatetuple is to aggregate at least 2 models together, the `in_models_keys` should be required and should have a minimum length of 2.

**Comment by samlesu** [comment]
As said [in the backend PR](https://github.com/SubstraFoundation/substra-backend/pull/189), there is no reason for adding this restriction. Aggregating nothing or aggregating a single model should be possible.
