### ISSUE TITLE
Add an option to deactivate local folder deletion

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-backend#204]
This is required as the current local folder deletion mechanism is not compatible with adding tuples to a "finished" compute plan.

**Comment by Kelvin-M** [comment]
In fact, there are multiple ways to do that (chaincode or backend). Deletion mechanism is triggered from a chaincode `event`, it should be better to add an option there to directly see in the smart contract if we keep or not the local folder. The backend will only delete local volume if the compute plan have this option enabled.
It will allow to enable or disable it for each compute plan.

**Comment by samlesu** [comment]
It has been implemented in https://github.com/SubstraFoundation/substra-backend/pull/205. We forgot to close the related issue.

It has been done as a quick fix in order to support an integration built on top of Substra.

A mission has been created to discuss the solution for a long term fix.
