### ISSUE TITLE
Deployment randomly fails (PVC claim not honored)

### ISSUE THREAD

**Issue by AurelienGasser** [SubstraFoundation/substra-backend#206]
I occasionally get this error (1 time out of ~10).

The pods stay pending forever.

![image(1)](https://user-images.githubusercontent.com/168382/78160183-9289ec80-7411-11ea-99be-3a5b888b2759.png)

![image (1)](https://user-images.githubusercontent.com/168382/78160181-9289ec80-7411-11ea-9b59-2738d84285fc.png)

![image (2)](https://user-images.githubusercontent.com/168382/78160179-91f15600-7411-11ea-8241-e85735e2eb40.png)

**Comment by Kelvin-M** [comment]
@AurelienGasser Did you reproduce this issue during the last month ?

**Comment by AurelienGasser** [comment]
@Kelvin-M No, but maybe the nightly tests did ! 

I'm fine with closing for now. We can always reopen if we see it again.
