### ISSUE TITLE
single-node compute plan: worker tries to delete missing image

### ISSUE THREAD

**Issue by AurelienGasser** [SubstraFoundation/substra-backend#253]
Setup: 
- Setup with 2 nodes
- We run a compute plan that only has training tasks on node 2

The worker in node 1 encounters an error: it tries to delete an image that doesn't exist:

```
ERROR 2020-05-27 19:38:56,487 substrapp.tasks.tasks 696 140190742099776 404 Client Error: Not Found ("reference does not exist")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/substra/algo_dc32f8dd?force=True&noprune=False
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/usr/src/app/substrapp/tasks/tasks.py", line 983, in remove_algo_images
     client.images.remove(algo_docker, force=True)
   File "/usr/local/lib/python3.6/dist-packages/docker/models/images.py", line 463, in remove
     self.client.api.remove_image(*args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
     return f(self, resource_id, *args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/docker/api/image.py", line 495, in remove_image
     return self._result(res, True)
   File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
     raise create_api_error_from_http_exception(e)
   File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation)
 docker.errors.NotFound: 404 Client Error: Not Found ("reference does not exist")
```

(After a quick investigation: it looks like we're not `catch` ing the correct exception type (`NotFound` instead of `ImageNotFound`)

**Comment by Kelvin-M** [comment]
I try to understand how this issue can be triggered but it should not :
https://github.com/SubstraFoundation/substra-backend/blob/master/backend/substrapp/tasks/tasks.py#L987:L993

If we look the code, we can see that (l.988) we call `client.images.get(algo_docker)` which can raise a `docker.errors.ImageNotFound` (that why we catch this exception). If the call is successful, `client.images.remove(algo_docker, force=True)` should not raise a `docker.errors.NotFound` as the image exists (unless a parallel process already remove it)

I look into the documentation (https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.remove), nothing is specify about potential exception that can be raised by this method.
Looking directly in the code (https://github.com/docker/docker-py/blob/5efe28149a2060ff64faab5d4c1566f4cb994792/docker/api/image.py#L484, https://github.com/docker/docker-py/blob/c6a33f25dc7fc172c69b8935e8c1e6b7aa44be8f/docker/errors.py#L13), `NotFound` is raised in all case not handled for `ImageNotFound` (https://github.com/docker/docker-py/blob/c6a33f25dc7fc172c69b8935e8c1e6b7aa44be8f/docker/errors.py#L24:L27)

Reading multiple stuff on "reference does not exist" from a docker image removal suggests (https://github.com/moby/moby/issues/26862) that backend is trying to remove an image that was already removed (sharing the same image as another tag).

I think we can safely update https://github.com/SubstraFoundation/substra-backend/blob/master/backend/substrapp/tasks/tasks.py#L992 to 
```python
    except (docker.errors.ImageNotFound, docker.errors.NotFound):
```

**Comment by AurelienGasser** [comment]
@Kelvin-M +1 it seems like a good solution
