### ISSUE TITLE
[Edge case] Crash when composite traintuple head and trunk models are identifcal

### ISSUE THREAD

**Issue by AurelienGasser** [SubstraFoundation/substra-backend#291]
For a composite traintuple, if the head and the trunk out models are identical, the saving fails.
﻿
That's because not only do the two models have the same composite traintuple key (expected), they ALSO have the same value.

The hash is computed from the traintuplekey and the value. So the hashes are the same for the head and the trunk model, which leads to a pkhash conflict.

There was [an aborted attempt at fixing this issue](https://github.com/SubstraFoundation/substra-backend/pull/290).

**Comment by Esadruhn** [comment]
Also once the fix is done in the default mode we can fix this in the debug mode (on the substra repo).
