### ISSUE TITLE
Can't get a stable deployment using line 0.7.1 of the compatibility table

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra-backend#350]
I'm trying to run hlf-k8s using the latest line on the compatibility table. I'm running Ubuntu Server 18.05.4, with the following software versions:

- minikube `1.9.2`
- docker `19.03.13`
- kubernetes `1.15.11`
- hlf-k8s `0.0.13`
- substra-chaincode `0.0.11`
- skaffold `1.8.0`
- helm `3.4.1`
- kubectl `1.18.0`

I'm using a remote (by setting `chaincode[0].src` to `https://github.com/SubstraFoundation/substra-chaincode/archive/0.0.11.tar.gz` in the `skaffold.yaml` file) version of the chaincode repository when deploying hlf-k8s.
I've changed the hlf-k8s chart's `requirements.yaml` file to replace `https://kubernetes-charts.storage.googleapis.com` with `https://charts.helm.sh/stable`, and then ran a

```
helm dependency update $absolute_path_to_chart
```

I then run the `skaffold run` but the last 3 deployments fail:

```
- org-2:deployment/backend-org-2-substra-backend-server failed. [2/16 deployment(s) still pending] Error: could not stabilize within 10m0s: context deadline exceeded.
- org-2:deployment/backend-org-2-substra-backend-registry-prepopulate-0 failed. [1/16 deployment(s) still pending] Error: could not stabilize within 10m0s: context deadline exceeded.
- org-1:deployment/backend-org-1-substra-backend-server failed. Error: could not stabilize within 10m0s: context deadline exceeded.
```

If I wait long enough all pods end up stabilizing with `org-1/network-org-1-peer-1-hlf-peer` giving the following message every 3 seconds:
```
2020-11-18 16:05:09.668 UTC [endorser] callChaincode -> INFO fb7 [yourchannel][862c9842] Entry chaincode: name:"lscc"
2020-11-18 16:05:09.701 UTC [endorser] callChaincode -> INFO fb8 [yourchannel][862c9842] Exit chaincode: name:"lscc"  (33ms)
2020-11-18 16:05:09.703 UTC [comm.grpc.server] 1 -> INFO fb9 unary call completed grpc.service=protos.Endorser grpc.method=Process Proposal grpc.peer_address=172.17.0.28:60000 grpc.peer_subject="CN=user,OU=peer,O=Hyperledger,ST=North Carolina,C=US" grpc.code=OK grpc.call_duration=35.880409ms
```

I then try the titanic example, login works and I manage to upload the objective and train_algo_random_forest but the traintuple remains stuck on `doing`. If I check my pods I have a new `kaniko-algo` pod with the following logs (blocked on `python3 algo.py`):
```
INFO[2074] ADD algo.py .
INFO[2074] Taking snapshot of files...
INFO[2074] ENTRYPOINT ["python3", "algo.py"]
stream closed
```
When it comes to the worker pod it seems to be waiting for the kaniko pod to finish processing:
```
[dc718953] - INFO - Waiting for pod kaniko-algo-e8cb987c...
```

**Comment by Kelvin-M** [comment]
You should share substra-backend-* logs to see what is the problem for no stabilization.
Moreover, what's the ressources allocated for minikube ?

**Comment by AurelienGasser** [comment]
Closing this inactive issue. Feel free to reopen if still relevant.
