### ISSUE TITLE
Missing tools support for the skaffold setup

### ISSUE THREAD

**Issue by AurelienGasser** [SubstraFoundation/substra-backend#38]
Currently, several tools don't support the skaffold setup:

1. [ ] titanic examples
2. [x] `generate_assets.py`
3. [x] `populate.py` (missing documentation)

**Comment by Kelvin-M** [comment]
For `populate.py`, you should use `populate.py -s -a` :)

**Comment by Kelvin-M** [comment]
For `generate_assets.py`, yes I think it's not compatible with skaffold, but by looking into `populate.py`  we can make an update to make it work quickly =)

**Comment by Kelvin-M** [comment]
For titanic examples, can you provide a link ?

**Comment by AurelienGasser** [comment]
@Kelvin-M 

Regarding the populate, the `-s -a` options are undocumented AFAIK. Currently, if someone using skaffold follows the README steps, the populate raises errors :/ A few edits to the README should be a good-enough fix!

Regarding the titanic examples, they use a config file that points to the docker-compose URL scheme. To run the titanic examples with skaffold, the config needs to be manually edited.

**Comment by Kelvin-M** [comment]
@AurelienGasser  I've done a improvement for the `populate.py` here : https://github.com/SubstraFoundation/substra-backend/pull/59

**Comment by Kelvin-M** [comment]
@AurelienGasser Where are we on this one :) ?

**Comment by AurelienGasser** [comment]
@Kelvin-M AFAIK no progress has been made. I think it could use more discussion: currently, it's not very clear what we want to do for the titanic examples and `generate_assets.py`. Some options would be: 1. Stop using the docker-compose config by default; 2. Keep support of both docker-compose and skaffold and add an option (If so, which option is default?)

**Comment by jmorel** [comment]
The generate_assets.py has already been updated to support the skaffold setup (using the `-s` option). But you're absolutely right in that we don't have a solution for the titanic examples.

**Comment by Kelvin-M** [comment]
So do we have a solution for titanic examples ?
As titanic example are not in this repo we may close or move this issue to the relevant repo ?

**Comment by jmorel** [comment]
We didn't take the time to think about it, but with @natct10 joining us, this should now move forward!

You're right about the issue being in the wrong repository though, I created a new more specific issue in the examples repo: https://github.com/SubstraFoundation/substra/issues/74
