### ISSUE TITLE
MVCC read conflict when reporting the success of a task

### ISSUE THREAD

**Issue by camillemarini** [SubstraFoundation/substra-backend#67]
Hello,

It looks like a `MVCC READ CONFLICT` occurred when registering the success of a training task. Attached are the logs. 
[logs.txt](https://github.com/SubstraFoundation/substra-backend/files/3937155/logs.txt)
For the context, I had submitted two `composite_traintuples` and an `aggregatetuple` with `inmodels` the two `composite_traintuples`. The error occured for one of the two `composite_traintuple`.

I am not sure to understand why we get it here. Is it because when logging the success of this task, when updating the status of its child (the `aggregatetuple`), it reads an older version of the other parents (the other `composite_traintuple`) which status has been updated at the same time ?

Couldn't we add a retry mechanism in order to fix this ?

**Comment by samlesu** [comment]
Retry when updating tuple status already exists in case of MVCC conflicts. It is deactivated in dev mode. That could explain the above issue.

IMHO, we should have the same behaviour in dev and in prod regarding the retry mechanism. It would help us to catch other issues that we may encounter later in production.
